### ISSUE TITLE
XDK Platform - Peripheral Verification

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#15]
<a href="https://github.com/BoykoKazakov"><img src="https://avatars1.githubusercontent.com/u/49551486?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BoykoKazakov](https://github.com/BoykoKazakov)**
_Thursday Jul 11, 2019 at 08:19 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/152_

----

Verify peripherals on the MCU are working properly based on examples.
Implicitly this verifies functionality of I2C

- [X] LED API
- [X] Button API
- [X] BMA280 API (Accelerometer)
- [X] BMG160 (Gyroscope)
- [ ] BMI160 (Accelerometer+ Gyro)
- [X] BME280 (Barometer+ Humidity)
- [x] BMM150 (Compass)
- [x] MAX44009 (Ambient Light)
- [x] USB CDC
- [x] Wifi

**Comment by HansUweRempler** [comment]
<a href="https://github.com/bierkandt-bosch"><img src="https://avatars2.githubusercontent.com/u/50450124?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bierkandt-bosch](https://github.com/bierkandt-bosch)**
_Wednesday Jul 31, 2019 at 07:13 GMT_

----

* Boyko working on Gyroscope
* Andrey working Accelerometer
* Currently problems with I2C (root cause unclear)
**  Arbitration issue sometime when using more than one  sensor at a time

**Comment by HansUweRempler** [comment]
<a href="https://github.com/bierkandt-bosch"><img src="https://avatars2.githubusercontent.com/u/50450124?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bierkandt-bosch](https://github.com/bierkandt-bosch)**
_Tuesday Oct 15, 2019 at 08:24 GMT_

----

Milestone closing:
- Currently on hold as focusing on ICD
=> move to backlog
