### ISSUE TITLE
Define integration test framework

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#17]
<a href="https://github.com/bierkandt-bosch"><img src="https://avatars2.githubusercontent.com/u/50450124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bierkandt-bosch](https://github.com/bierkandt-bosch)**
_Thursday Aug 08, 2019 at 11:43 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/193_

----

Define and agree on integration test framework e.g.
- [x] how to test SPI on different boards (with different MCUs) --> this is only a planning (evaluation) and not a doing
==> MCU loopback
- [ ] where to store the integration tests? --> part of code repo, documentation of integration tests tbd. (Hugo or markdown in code?), results accessible via Jenkins
==> essentials\test\integration\specs
==> ref HW (board) integration test spec not defined, yet
==> Jenkins not defined, yet
- [ ] Reuse existing integration test framework --> as a start (due to critical project status right now)

- [x] Make integration testing public or not? --> yes, see G1 slides "Whats part of CDDK open source"

Info: strong interest of AWS on that vs. benefit for other Bosch parties (e.g. PS with OEMs) to re-use and run own integration tests.
