### ISSUE TITLE
CI setup @ Eclipse Foundation

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#2]
<a href="https://github.com/yongbosch"><img src="https://avatars1.githubusercontent.com/u/47750708?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yongbosch](https://github.com/yongbosch)**
_Friday May 24, 2019 at 08:35 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/62_

----

Focus on compile and running unit tests, for integration testing use Bosch internal Jenkins (#176)
- [ ] Define and agree on CI approach => duplicate what we have Bosch internally (Docker Image)
- [ ] Define Jenkins at Eclipse Foundation (e.g. mails for build results?)
- [ ] Setup Jenkins at Eclipse Foundation?
