### ISSUE TITLE
Move to EF infrastructure

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#26]
<a href="https://github.com/bierkandt-bosch"><img src="https://avatars2.githubusercontent.com/u/50450124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bierkandt-bosch](https://github.com/bierkandt-bosch)**
_Wednesday Sep 25, 2019 at 11:31 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/284_

----

- [ ] update links in readme.md once Hugo server at EF is available so we know the correct URLs
- [ ] check version number readme.md and ensure it is correct
  - [x] major benefits and content of the ICD release --> see RELEASE_NOTES.md
  - [x] Updated known limitations (what can be done and especially can not be done with upcoming release) --> see RELEASE_NOTES.md
- [ ] Check changelog.md and ensure it is correct and complete
- [ ] Move issues and project from cddk-oss repo to EF Kiso repo
- [ ] add section "Open issues" to point to EF github Kiso Issue Section

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Thursday Jan 16, 2020 at 13:18 GMT_

----

I'm working on moving the issues and the other project details. There a nice Python project available for this: https://github.com/IQAndreas/github-issues-import
`python3 gh-issues-import.py --config config.ini --all --ignore-milestone`

Unfortunately, with this, the closed issues will be created new (with a [CLOSED] prefix) and remain open. Thus, I'm looking into transferring only the open issues and stripping the closed issues.

And, the milestone won't be transferred at all. So, I'll be recreating them in the public repo.
