### ISSUE TITLE
Address open organisational issues (after ICD)

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#27]
<a href="https://github.com/bierkandt-bosch"><img src="https://avatars2.githubusercontent.com/u/50450124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bierkandt-bosch](https://github.com/bierkandt-bosch)**
_Sunday Sep 29, 2019 at 20:18 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/294_

----

Address open organisational issues especially the ones demanded by Project Review Board in Q4/2019 and before next release
- [x] Regular Stakeholder Meeting (after agreement) --> 2x/year, first meeting scheduled for 30.01.20
- [ ] Involvement of RBEI
- [ ] Provide reasoning for unit test coverage selection and thresholds
- [ ] Revise roadmap (linked to goals & showing benefits, aligned with Kiso Steering Committee)
- [x] Finalize financing for 2020 --> done (critical, not all of the Kiso core team members are financed by Kiso budget throughout 2020 with 100%
- [ ] PEP topics which are not covered by MM SW PEP are addressed
  - Discuss and align approach with whole team
- [ ] Add an EPQ to team
- [ ] Clarify involvement of QMM (required? which one?)
- [ ] Define package transfer process from CDDK to Kiso (e.g. CDDK packages are frozen once moved to Kiso)
