### ISSUE TITLE
Handover CGW Mita Platform to maintainer

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#3]
<a href="https://github.com/wegendt-bosch"><img src="https://avatars0.githubusercontent.com/u/38556444?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wegendt-bosch](https://github.com/wegendt-bosch)**
_Monday May 27, 2019 at 08:02 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/68_

----

- [ ] setup development environment
- [ ] explain build process
- [ ] (?) adjust workbench setup(, remove BCX specific code)
- [ ] have a look at code generators
- [ ] have a look at program model representation (program -> function definitions, event handlers, ...)

**Comment by HansUweRempler** [comment]
<a href="https://github.com/wegendt-bosch"><img src="https://avatars0.githubusercontent.com/u/38556444?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wegendt-bosch](https://github.com/wegendt-bosch)**
_Monday May 27, 2019 at 13:26 GMT_

----

[Branch](https://github.com/Bosch-AE-SW/cddk-oss/tree/68-handover-cgw-platform)
