### ISSUE TITLE
Further improve documentation (strategy and Doxygen)

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#36]
<a href="https://github.com/bierkandt-bosch"><img src="https://avatars2.githubusercontent.com/u/50450124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bierkandt-bosch](https://github.com/bierkandt-bosch)**
_Tuesday Oct 15, 2019 at 07:18 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/330_

----

What else there is to improve documentation?
- [x] Define documentation strategy (what goes in .md files, what on hugo, what in Hugo server, what in doxygen, is there a wiki somewhere) --> see project review board #4 slides (Documentation)
- [ ] Restructure doxygen (e.g. in essentials first docu from .h then from .c might confuse user)
  - [x] create examples section
  - [x] write proper documentation for each example (e.g purpose of the example, HW ressources needed, how to build it and flash it)in the @details section
  - [x] create boards section
  - [ ] write proper documentation for each board (e.g. Introduce the board, the MCU, the 
peripherals supported, those not supported, where to buy etc.)
  - [ ] write documentation for example c-cellular

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Wednesday Oct 16, 2019 at 13:04 GMT_

----

FYI, I setup a Hugo server: [kiso.rempler.de:1313](kiso.rempler.de:1313)
It's an Azure Ubuntu VM with a cronjob that pulls the Kiso repo every 5min. I propose to use that server temporary until we have the Eclipse Foundation setup ready. Thus, all links in our docu can point there instead of leading to nowhere.

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Wednesday Oct 16, 2019 at 13:41 GMT_

----

Also, I edited [https://github.com/Bosch-AE-SW/cddk-oss/wiki](https://github.com/Bosch-AE-SW/cddk-oss/wiki) and pointed to the Hugo docu.

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Tuesday Dec 10, 2019 at 16:21 GMT_

----

@laithnasser and @khalifima
- [ ] Why is the above checkbox "Restructure doxygen [...]" and all its sub-tasks ticked if you're still working on "#330 restructuring the doxygen documentation #419"?
- [ ] And why is this issue still in the backlog and not in the "in progress column"?

**Comment by HansUweRempler** [comment]
<a href="https://github.com/laithnasser"><img src="https://avatars2.githubusercontent.com/u/56630901?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [laithnasser](https://github.com/laithnasser)**
_Wednesday Dec 11, 2019 at 08:08 GMT_

----

@HansUweRempler  
i think i ticked them all by wrong , and i just know that i should change it to in progress. sorry for that .
