### ISSUE TITLE
CommonGateway CI Integration Test Setup

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#44]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HansUweRempler](https://github.com/HansUweRempler)**
_Monday Nov 18, 2019 at 07:32 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/387_

----

**Is your feature request related to a problem? Please describe.**
The Cellular SW module has been broken during unit testing improvement and nobody realized this. Only after manual setup for the BoCSE demo this has been noticed.

**Describe the solution you'd like**
We must have an automated (continuous integration) setup to know the health status of our master branch. This setup needs to be
* Prio a) working with Bosch infrastructure
* Prio b) extendable with additional reference HW
* Prio c) working with future Eclipse Foundation infratructure

- [ ] First Kiso RefHW Bosch CommonGateway connected to Jenkins agent (Beaglebone) for flashing and executing integration tests
- [ ] write integration test spec
  cddk-oss/boards/CommonGateway/test/specs
  e.g., read out MCU id
  e.g., read out BMA350 id
  e.g., read out Ublox SARA IMEI
- [ ] run integration tests on the HW
  cddk-oss/boards/CommonGateway/test/integration
- [ ] integration test results visible to [Kiso Jenkins](https://rb-jmaas.de.bosch.com/software-campus/view/Kiso-Dashboard/)
- [ ] Hugo documentation update

**Describe alternatives you've considered**
We have already a CI setup for unit tests etc.. The Ku server and the Beaglebones are prepared for XDK integration tests.

**Additional context**
Whoever can participate on this task shall please do so. Only if there is now work available for making this happen another topic shall be addressed. This user story here is the main target for Kiso monthly 12.19.

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Wednesday Nov 20, 2019 at 15:33 GMT_

----

I had an interesting discussion today at the BoCSE about how we could have our Jenkins dashboard, i.e., the CI results public available.
If we connect the Beaglebones to the development network (which I think they maybe already are) using the white router boxes (transparent proxy) they could open up (and keep it open) a ssh tunnel - maybe during startup - to a Jenkins master outside BGN. I can offer to support with a Azure VM until we have the EF infrastructure and their Jenkins master available. On the VM we could quickly install and run a Jenkins instance to try out the connection to our Bosch development Beaglebones.

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Friday Nov 22, 2019 at 05:57 GMT_

----

FYI, I just finished setting up a BGN external Jenkins. It's available via http://kiso.rempler.de:9090/ - I will add it to the README.md later. I need your support in configuring it for our GitHub repo.
