### ISSUE TITLE
Code complexity metric

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#54]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HansUweRempler](https://github.com/HansUweRempler)**
_Wednesday Dec 04, 2019 at 12:46 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/412_

----

**Is your feature request related to a problem? Please describe.**
We can't see how complex or uncomplex our code is. This is necessary for most of our quality goals (understandability, useability, maintainabilty, testability, etc.).

**Describe the solution you'd like**
Automated metric that can be accessed via continuous integration Jenkins dashboard. The tooling to automate this can be discussed with our workplace team. Also, which measurements are to be accounted into code complexity should be defined via experience from workplace team projects.

**Describe alternatives you've considered**
We're (kind of) using CLang-tidy, e.g., "Function-size" but w/o configuring it, i.e., not activating it. This report would then show us if we're above or below our own set watermark level.

**Additional context**
This is not concerning defining the watermark or complexity level that's acceptable or not. Defining the watermark level can be taken 

- [ ] Define and document (Hugo) complexity measurements (at least one, e.g., cyclomatic complexity).
  Expected output: Hugo page that describes which complexity measures we're using.
- [ ] Automated way to analyse above.
  Expected output: complexity metrics are automatically and continuously generated for latest master branch.
- [ ] Status to be publicly visible, e.g., Jenkins dashboard
  Expected output: metric reports are accessible via browser for everbody
