### ISSUE TITLE
Configure (enable) Clang readability check

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#55]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HansUweRempler](https://github.com/HansUweRempler)**
_Wednesday Dec 04, 2019 at 17:36 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/415_

----

**Is your feature request related to a problem? Please describe.**
The code complexity is part of nearly all of Kiso's [quality goals](https://inside-docupedia.bosch.com/confluence/display/ASCMP/1.+Project+Overview#id-1.ProjectOverview-Qualitygoals), e.g., Simplicity, Testability ad Maintainability. For now, this is not automatically checked (because the watermark level is not defined, yet).

**Describe the solution you'd like**
Activate in [Kiso's Clang config ](https://inside-docupedia.bosch.com/confluence/display/ASCMP/3.1.1+Static+Code+Analysis) the [readability-function-size](https://clang.llvm.org/extra/clang-tidy/checks/readability-function-size.html#options) options with reasonable proposals for the threshold values
- LineThreshold
- StatementThreshold
- BranchThreshold
- ParameterThreshold
- NestingThreshold
- VariableThreshold
 
**Describe alternatives you've considered**
Use another (commercial) like, e.g., SonarCube and the therein defined default values.

**Additional context**
The reasonable proposals for the threshold values should comply to the state-of-the-art. References to SonarCube's default values or other project's best practices shall be considered.

- [x] Proposal of values for above listed options
  Expected output: reasonable values in Kiso team sync
- [x] Activate Clang config readability-function-size by setting values for all it's options
  Expected output: clang Jenkins automated check
- [x] Wiki page documentation update https://inside-docupedia.bosch.com/confluence/display/ASCMP/3.1.1+Static+Code+Analysis
  Expected output: Wiki page update for red text

**Comment by HansUweRempler** [comment]
<a href="https://github.com/elbosch"><img src="https://avatars0.githubusercontent.com/u/36697481?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elbosch](https://github.com/elbosch)**
_Thursday Dec 05, 2019 at 17:07 GMT_

----

@SajaKhdour and @elbosch have tested the feature. 
we got warnings for exceeding limits of line count, branch count, and nesting count. As per our current clang policy we get an unstable build as we mark those things as failed tests. 

another procedure could be to change the approach slightly: say we store the artefacts from clang-tidy but we define in our .clang-tidy file by using: WarningsAsErrors: '' and add those checks that we  actually want the build to fail.

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Tuesday Dec 10, 2019 at 16:33 GMT_

----

@elbosch please move this to "in progress" column if you're actually working on this issue. Thanks.

**Comment by HansUweRempler** [comment]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansUweRempler](https://github.com/HansUweRempler)**
_Wednesday Dec 11, 2019 at 12:54 GMT_

----

Seems that SonarQube reporting is superior to clang-tidy.
SonarCloud from Eclipse Foundation is charging for closed source projects (10EUR/month 100k lines of code) like this one here and the free SonarCloud version needs an open source repo --> work in progress: github.com/eclipse/kiso

**Comment by HansUweRempler** [comment]
<a href="https://github.com/sebastianpfischer"><img src="https://avatars0.githubusercontent.com/u/16876251?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sebastianpfischer](https://github.com/sebastianpfischer)**
_Thursday Jan 16, 2020 at 10:24 GMT_

----

Discussed with @elbosch :
•	key: readability-function-size.LineThreshold
value: '120'
•	key: readability-function-size.BranchThreshold
value: '15'
•	key: readability-function-size.NestingThreshold
value: '7'
•	key: readability-function-size.ParameterThreshold
value: '8'
•	key: readability-function-size.StatementThreshold
value: '100'
•	key: readability-function-size.VariableThreshold
value: '8'
•	key: readability-inconsistent-declaration-parameter-name.Strict
value: '0'

**Comment by HansUweRempler** [comment]
<a href="https://github.com/sebastianpfischer"><img src="https://avatars0.githubusercontent.com/u/16876251?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sebastianpfischer](https://github.com/sebastianpfischer)**
_Thursday Jan 16, 2020 at 10:26 GMT_

----

done in #418
