### ISSUE TITLE
Harmonize the tooling versions

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#59]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HansUweRempler](https://github.com/HansUweRempler)**
_Wednesday Dec 11, 2019 at 20:02 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/425_

----

**Is your feature request related to a problem? Please describe.**
We have an inconsistency in our tooling versions.

**Describe the solution you'd like**
Define versions for the quick start section and use the same in the CI Docker image for the following:
- [ ] arm-none-eabi
  Expected outcome: version number
- [ ] CMake
  Expected outcome: version number
- [ ] git
  Expected outcome: version number
- [ ] Use above versions in quick start guide http://kiso.rempler.de:1313/3.-user-guide/quick_start/
  Expected outcome: updated docu
- [ ] Use above versions in CI Docker image https://github.com/Bosch-AE-SW/cddk-oss/blob/master/ci/docker/Dockerfile
  Expected outcome: Dockerfile with explicit version numbers

**Describe alternatives you've considered**
n/a

**Additional context**
Follow-up to https://github.com/Bosch-AE-SW/cddk-oss/issues/381
