### ISSUE TITLE
Common Gateway simple integration tests

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#61]
<a href="https://github.com/HansUweRempler"><img src="https://avatars2.githubusercontent.com/u/42936658?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HansUweRempler](https://github.com/HansUweRempler)**
_Thursday Dec 12, 2019 at 16:35 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/428_

----

**Is your feature request related to a problem? Please describe.**
The CI HW integration test framework is going on and on its way to get finalized. After the framework is ready we need to define and implement tests.

**Describe the solution you'd like**
Take the first reference HW manual tests "Test Section 1: CommonGateway Manual Tests" and transfer them to CI HW integration tests, see https://github.com/Bosch-AE-SW/cddk-oss/blob/master/examples/CommonGateway/tests/TestSuite_IcdFeatures.md
- [ ] rename and move TestSuite_IcdFeatures.md
  Expected outcome: renamed file and new dir structure
```
  TestSuite_CommonGatewayManualTests.md in
  cddk-oss/examples/CommonGateway/test/manual/specs
  cddk-oss/examples/CommonGateway/test/integration
  cddk-oss/examples/CommonGateway/test/integration/source
  cddk-oss/examples/CommonGateway/test/integration/specs
```
- [ ] write document with automated test suite (not all manual tests make sense for simple auto testing)
  Expected outcome: new file
```
  TestSuite_CommonGatewayCITests.md in
  cddk-oss/examples/CommonGateway/test/integration/specs/
```
- [ ] implement the above test cases
  Expected outcome: source code with test suite in
```
  xxx.[c|h]
  cddk-oss/examples/CommonGateway/test/integration/source
```

**Describe alternatives you've considered**
Take a reference from the SW module "essentials" integration tests.

**Additional context**
This could be a special task (with guidance and supervision) for one of our interns Layth to give him a new challenge :-).
