### ISSUE TITLE
STM32F7: BSP

### ISSUE THREAD

**Issue by HansUweRempler** [HansUweRempler/kiso#7]
<a href="https://github.com/yongbosch"><img src="https://avatars1.githubusercontent.com/u/47750708?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yongbosch](https://github.com/yongbosch)**
_Friday Jun 28, 2019 at 13:39 GMT_
_Originally opened as https://github.com/Bosch-AE-SW/cddk-oss/issues/125_

----

Generic reference HW dev kit pattern
* STM32F7: vendor library as 3rd party
* STM32F7: BSP --> this issue here
* STM32F7: config
* STM32F7: HAL MCU in essentials
* STM32F7: LED example
* STM32F7: integration test setup (flashing, dummy test)

- [x] take it from https://bcds01.de.bosch.com/bitbucket/projects/XDK/repos/ivas_bsp/browse/source
- [ ] port it to kiso
- [ ] update copyright header and license
- [ ] pass compile

**Comment by HansUweRempler** [comment]
<a href="https://github.com/bierkandt-bosch"><img src="https://avatars2.githubusercontent.com/u/50450124?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bierkandt-bosch](https://github.com/bierkandt-bosch)**
_Wednesday Jul 31, 2019 at 07:30 GMT_

----

- Currently adapting to CommonGateway BSP approach (use same patterns)
- Open
  - Test Interface (interface for logging) 
  - Interfaces for SPI, UART and I2C
  - Documentation in code
